# Generated by Django 2.1.15 on 2021-09-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reipe',
            new_name='Recipe',
        ),
    ]
